package main

// 同一个包下可以直接引用, 通过go run . 或 go run main.go test.go 来执行
func main() {
	// TryArrays()
	// TryValues()
	// TryVariables()
	// TryConstants()
	// TryFor()
	// TryIfElse()
	// TrySwitch()
	// TrySlices()
	// TryMaps()
	// TryRange()
	// TryFunctions()
	// TryClosures()
	// TryPointers()
	// TryStructs()
	// TryMethods()
	// TryInterfaces()
	// TryErrors()
	// TryGoroutines()
	// TryChannels()
	// TryChannelSynchronization()
	// TryChannelDirections()
	// TrySelect()
	// TryTimeouts()
	// TryNonBlockingChannelOperations()
	// TryCloseChannel()
	// TryTimersAndTickers()
	// TryWorkPools()
	// TryWaitGroups()
	// TryRateLimiting()
	// TryAtomicCounters()
	// TryMutexes()
	// TryStatefulGoroutines()
	// TryDefer()
	// TryContext()
	// TryReflect()
	// TryContextCancellation()
	// TryContextTimeouts()
	TryContextValues()
}
